publish-backend/.dockerignore
publish-backend/Dockerfile

Checklist:
Closes #XXXXX
---
I'm still getting error when I try to `docker run`.
I took the Dockerfile from: https://docs.strapi.io/dev-docs/installation/docker#development-dockerfile

(Draft) Add Dockerfile for Strapi app

---

publish-frontend/src/components/post-form.jsx

feat: add go back button to editor

---

publish-frontend/src/components/post-form.jsx
publish-frontend/src/lib/tags.js

TODO after this pr:
1. Make tag slug or name a unique identifier
2. Refresh list of tag options without needing to refresh the page
3. Check if tag already exists
--
Should tag be added to post after creation?
closes #145
closes #47

feat: create new tag from post editor

---

.github/workflows/lint.yml
publish-backend/.eslintrc
publish-backend/config/env/test/database.js
publish-backend/package-lock.json
publish-backend/package.json
publish-backend/src/api/custom-post/controllers/custom-post.js
publish-backend/src/api/custom-post/services/custom-post.js
publish-backend/src/extensions/users-permissions/strapi-server.js
publish-backend/tests/app.test.js

Checklist:
@sidemt I disabled the linter in custom-post because I wanted to keep this PR small. If you know what `...rest` should contain I think using lodash's pick would be the way to go. That way seems better since we don't really care what we're discarding, only what we're keeping!

chore: add eslint to backend

---

publish-frontend/src/lib/tags.js
publish-frontend/src/pages/tags/index.js

feat: tags list page

---

publish-frontend/src/components/post-form.jsx
publish-frontend/src/pages/posts/preview/[postId].js

feat: requested changes on preview

---

publish-backend/config/sync/user-role.authenticated.json
publish-backend/src/seed/index.js
publish-frontend/src/lib/invite-user.js
publish-frontend/src/lib/users.js
publish-frontend/src/pages/users/index.js

Checklist:
Closes #126 
* Do we want to keep the `last seen` for active users?
* Any specific color preferences for role badges or the same one as ghost is good ie. grey for contributor and purple for editor?

feat: users list page

---

publish-frontend/src/components/post-form.jsx

feat: open and close post menu

---

publish-backend/package-lock.json
publish-backend/package.json

Checklist:
Closes #XXXXX
Remove packages that were added while following the quick start guide but are not used now.

Chore: remove unused packages

---

publish-frontend/src/components/post-form.jsx
publish-frontend/src/components/tiptap.jsx
publish-frontend/src/pages/posts/index.js

feat: instantly create new post by pressing new post button

---

publish-frontend/src/components/tiptap.jsx

fix: toggle heading instead of set heading

---

publish-frontend/src/components/tiptap.jsx

fix: remove heading icons froms menu dropdown

---

publish-frontend/src/components/post-form.jsx
publish-frontend/src/lib/invite-user.js
publish-frontend/src/lib/posts.js

Checklist:
Nothing serious here, I just spotted some issues when going through the codebase.

fix: hook warnings and data stringification

---

publish-frontend/package-lock.json
publish-frontend/package.json
publish-frontend/src/components/tiptap.jsx

feat: word count post editor

---

publish-frontend/src/pages/tags/index.js
publish-frontend/src/pages/tags/new.js

Checklist:
Closes #XXXXX
Ref - https://github.com/freeCodeCamp/publish/pull/199#discussion_r1334040655
Thanks for catching this @ojeytonwilliams

fix: CSR new tag page

---

publish-frontend/src/pages/posts/index.js

Checklist:
Closes #XXXXX
I was getting `createPost Failed` error when clicking the New Post button. It turned out that `JSON.stringify` is already done inside the createPost method so we don't need it here.

fix(frontend): fix createPost error

---

publish-frontend/src/components/post-form.jsx

feat: ask user to save changes before leaving page

---

publish-backend/config/sync/admin-role.strapi-super-admin.json
publish-backend/config/sync/core-store.plugin_content_manager_configuration_content_types##api##post.post.json
publish-backend/config/sync/core-store.plugin_content_manager_configuration_content_types##api##tag.tag.json
publish-backend/config/sync/core-store.plugin_content_manager_configuration_content_types##plugin##users-permissions.user.json
publish-backend/src/api/post/content-types/post/schema.json
publish-backend/src/api/tag/content-types/tag/schema.json
publish-backend/src/extensions/users-permissions/content-types/user/schema.json

Checklist:
Closes #XXXXX
Related with: https://github.com/freeCodeCamp/scripts/pull/210
Add `ghost_id` columns to the models that will be imported from Ghost. Just in case if we need to find the corresponding data from the old database later.

feat(backend): add ghost_id column

---

docs/README.md
publish-backend/.env.example
publish-backend/package.json
publish-backend/scripts/seed.js
publish-backend/src/api/invited-user/content-types/invited-user/lifecycles.js
publish-backend/src/index.js

Checklist:
This allows us to simplify the startup a fair bit.

refactor: decoupling seeding from strapi bootstrap

---

publish-frontend/src/components/post-form.jsx
publish-frontend/src/pages/posts/[postId].js

fix: editor migration issues

---

publish-backend/config/sync/admin-role.strapi-super-admin.json
publish-backend/config/sync/core-store.plugin_content_manager_configuration_content_types##api##post.post.json
publish-backend/src/api/post/content-types/post/schema.json
publish-backend/src/api/post/controllers/post.js
publish-backend/tests/helpers/fixtures.js
publish-backend/tests/post/index.js

fix: add code injection fields

---

publish-backend/.lintstagedrc
publish-frontend/.lintstagedrc

Otherwise lint-staged will fail if prettier encounters something it cannot format.
Checklist:

fix: have prettier ignore unknown files

---

publish-backend/package.json

fix: init script for publish-backend

---

apps/backend/package.json
apps/cron/package.json
apps/frontend/package.json
apps/frontend/sample.env
docs/README.md

Checklist:
This lets us remove one more setup step and should be safe. Anyone's existing .env files are respected and docker already ignores .env.

chore: simplify initial setup

---

apps/frontend/sample.env
apps/frontend/src/pages/api/auth/[...nextauth].js

Checklist:
Again this is part of https://github.com/freeCodeCamp/publish/pull/304, but I wanted to make it more visible.

feat: allow email-password auth in built site

---

.github/workflows/build.yml

- feat: build images in workflow
- chore: use staging environment
Checklist:
Adds a workflow file to allow us to upload images to the Digital Ocean container registry.

feat: add workflow to build images

---

apps/backend/package.json

That allows us to keep init for tasks that do not require a database
connection.
Checklist:
Closes #XXXXX

build: move config config-sync import to seed

---

apps/backend/package.json
apps/cron/package.json
apps/frontend/package.json
turbo.json

chore: add format script

---

.github/workflows/test.yml
apps/backend/package.json
apps/backend/src/api/post/controllers/post.js
apps/backend/tests/custom-post/index.js
package-lock.json
package.json

- test: add jest tests to CI
- test: bump node version for tests
Checklist:
Closes #XXXXX

test: run jest tests in CI

---

apps/backend/src/api/post/controllers/post.js

Checklist:
Closes #XXXXX
Adding `console.error` to make it easier to debug errors that were found in staging server.

chore: add console.error

---

apps/frontend/src/lib/theme.js
apps/frontend/src/pages/_app.js

Checklist:
Closes #XXXXX
This PR combines the theme config into the file Sem created in the darkmode PR so that it becomes easier to modify the theme in one place.

chore: combine theme config

---

e2e/.eslintrc.js
e2e/editor.spec.ts
e2e/helpers/user.ts
e2e/pages/users.ts
e2e/users.spec.ts

Checklist:
Followup to https://github.com/freeCodeCamp/publish/pull/417, but with all the lint rules enabled,

fix: use type-aware linting and apply fixes

---

e2e/contributor/posts.spec.ts
e2e/editor-drawer.spec.ts
e2e/editor.spec.ts

tests: reduce flakiness

---

apps/frontend/src/components/nav-menu.jsx
apps/frontend/src/components/tiptap.jsx
apps/frontend/src/pages/posts/index.js
apps/frontend/src/pages/tags/index.js
apps/frontend/src/pages/users/index.js

Checklist:
Closes #415
cc - @Sembauke

fix: dark mode colors
